"""Add menu_item table

Revision ID: 309eacab9a02
Revises: 9f3c1b8a0e12
Create Date: 2026-01-07 03:17:16.560355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '309eacab9a02'
down_revision: Union[str, Sequence[str], None] = '9f3c1b8a0e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cooking_tasks', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cooking_tasks', 'menu_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cooking_tasks', 'status',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("'queued'::character varying"))
    op.alter_column('ingredients', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ingredients', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('menu', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('menu', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'seat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("'created'::character varying"))
    op.alter_column('orders', 'total_cost',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_cost',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("'created'::character varying"))
    op.alter_column('orders', 'seat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('menu', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('menu', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ingredients', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ingredients', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cooking_tasks', 'status',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("'queued'::character varying"))
    op.alter_column('cooking_tasks', 'menu_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cooking_tasks', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
